adaptive_odom_filter:
  ros__parameters:
    enableFilter: true
    enableImu: true
    enableWheel: true
    enableLidar: true
    enableVisual: false
    filterFreq: "l"
    freq: 20.0

    alpha_lidar: 0.99
    alpha_visual: 0.999

    lidarG: 1.0
    wheelGVx: 0.001
    wheelGVy: 1.0
    wheelGWz: 40.0
    wheelOffset: 1.0e-5
    visualG: 0.1
    imuG: 1.0

    gamma_vx: 0.05
    gamma_omegaz: 0.01
    delta_vx: 0.0001
    delta_omegaz: 0.00001

    minIntensity: 0.0
    maxIntensity: 1.0

    lidar_type_func: 2
    visual_type_func: 2
    wheel_type_func: 1
    experiment: 0

    camera_type: 1
    imu_topic: "/imu/data"
    wheel_odom_topic: "/odom_with_cov"
    lidar_odom_topic: "/ekf_loam/laser_odom_with_cov"
    tracking_odom_topic: "/camera/odom"
    depth_odom_topic: "/camera/odom"
    left_camera_topic: "/t265/fisheye2/image_raw"
    right_camera_topic: "/t265/fisheye1/image_raw"
    color_camera_topic: "/d435i/color/image_raw"
    filter_odom_topic: "/ekf_loam/filter_odom_to_init"
    rtabmap_service_topic: "/rtabmap/reset_odom_to_pose"
    odom_frame_id: "chassis_init"
    base_frame_id: "ekf_odom_frame"
